name: itonatalaga
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/house.png
    - assets/activity1.png
    - assets/activity2.png
    - assets/activity3.png
    - assets/activity4.png
    - assets/opening.mp3